[en]
  languageName = "English"
  languageCode = "en-US"
  weight = 10
  [en.params]
    languageISO = "EN"

[pt]
  languageName = "Portuguese (Brazil)"
  languageCode = "pt-BR"
  weight = 20
  [pt.params]
    languageISO = "pt-BR"
