# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Conheça o time de vôlei do CMS, um grupo dinâmico e competitivo que se destaca por sua rapidez em quadra, espírito de equipe e excelência tanto em habilidades técnicas quanto em desempenho escolar, representando o Colégio Militar de Salvador com orgulho e paixão."
images = ['images/logo.svg','images/site-feature-image.png']
mainMenuLogo = "images/logo.svg"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = true
alertText = "Este site usa cookies necessários para garantir a funcionalidade adequada. <a class='alert-link stretched-link' href='/politica-de-privacidade'>Saiba mais sobre nossa Política de Privacidade</a>."

# Pre-footer
footerAbout = true
footerAboutTitle = "Few Words About Us"
footerAboutText = "We protect your website so you can provide a safe environment to build trust and improve the user experience of your visitors.<br/><br/>Salvus Site is the partner that you can rely on for preventive and reactive cybersecurity."

[options]
  bootStrapJs = true
  breadCrumb = true
  listCategoryFilter = true
  listTagFilter = true
